# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Granary < Formula
  desc "Export Granola meeting notes and transcripts to markdown"
  homepage "https://github.com/wassimk/granary"
  version "0.2.2"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/wassimk/granary/releases/download/v0.2.2/granary-Darwin-amd64.tar.gz"
    sha256 "08df8501b99ea1dec414ba902d9188fb6cd0b41672fb2cb960dbe532df888dd0"

    define_method(:install) do
      bin.install "granary"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/wassimk/granary/releases/download/v0.2.2/granary-Darwin-arm64.tar.gz"
    sha256 "19924ef411d50c3f89bb56606ece67b9e6d21cf03c28c43b266cff0a9a179d19"

    define_method(:install) do
      bin.install "granary"
    end
  end

  def caveats
    <<~EOS
      To start granary as a background service (exports every 6 hours):
        granary install

      To remove the background service:
        granary uninstall
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/granary version")
  end
end
