# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Granary < Formula
  desc "Export Granola meeting notes and transcripts to markdown"
  homepage "https://github.com/wassimk/granary"
  version "0.2.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/wassimk/granary/releases/download/v0.2.1/granary-Darwin-amd64.tar.gz"
    sha256 "655bb93b9cf4cf62df00b62a29bea9ff1f55e6900919447dc83aac4cd09de901"

    define_method(:install) do
      bin.install "granary"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/wassimk/granary/releases/download/v0.2.1/granary-Darwin-arm64.tar.gz"
    sha256 "4cbdac6e698e6102416da6df90fce71ef697a517de7c767addf2bfd2c028b2a0"

    define_method(:install) do
      bin.install "granary"
    end
  end

  def caveats
    <<~EOS
      To start granary as a background service (exports every 6 hours):
        granary install

      To remove the background service:
        granary uninstall
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/granary version")
  end
end
